<?php

/**
 * @file
 * Installs the better_formats module.
 *
 * Creates a database for use of multi-layered default formats and sets
 * default settings.
 */

/**
 * Implements of hook_install().
 */
function better_formats_install() {
  // Increase module weight to prevent compatibility issues.
  db_update('system')
    ->fields(array('weight' => 100))
    ->condition('name', 'better_formats')
    ->execute();
}
